data-type: Mongo

muted-blocked-commansd:
  - "/msg"
  - "/message"
  - "/reply"
  - "/r"

mongo:
  host: 127.0.0.1
  port: 27017
  database: bpunishments
  auth:
    enabled: false
    username: Username
    password: Password
